version: '3'

services: 
    nginx_lb:
        build: .
        ports: 
            - 9009:9009
    nginx_lb1:
        build: ./lb1
        ports: 
            - 8081:8081
    nginx_lb2:
        build: ./lb2
        ports: 
            - 8082:8082
    nginx_lb3:
        build: ./lb3
        ports: 
            - 8083:8083
    node1:
        build: app
        environment:
            - APP_ID=1
    node2:
        build: app
        environment:
            - APP_ID=2
    node3:
        build: app
        environment:
            - APP_ID=3